name: Profile cbds and nomad using optiprofiler, small

on:
  # Trigger the workflow on # # push or pull request
  # push:
  # Trigger the workflow manually
  # schedule:
  # - cron: '0 0 */4 * *'
  workflow_dispatch:

env:
    GFORTRAN_VERSION: 12

jobs:
  test:
    name: Profile BDS and nomad, small
    runs-on: ${{matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        dim: [small]
        with_optim_toolbox: [yes]
        solver: [cbds]
        competitor: [nomad]
        run_plain: [false]
        feature: [plain, perturbed_x0, perturbed_x0_1, perturbed_x0_10, noisy_1e-1, noisy_1e-2, noisy_1e-3, noisy_1e-4, truncated_1, truncated_2, truncated_3, truncated_4, permuted, linearly_transformed, random_nan_5, random_nan_10, random_nan_20, quantized, rotation_noisy_1e-1, rotation_noisy_1e-2, rotation_noisy_1e-3, rotation_noisy_1e-4]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout OptiProfiler
        uses: actions/checkout@v4
        with:
          repository: optiprofiler/optiprofiler
          ref: matlab
          path: optiprofiler

      - name: Clone MatCUTEst
        uses: actions/checkout@v4
        with:
            repository: matcutest/matcutest_compiled
            path: matcutest

      - name: Checkout Nomad
        uses: actions/checkout@v4
        with:
            repository: bbopt/nomad
            path: nomad   

      - name: Install Texlive
        run: sudo apt-get update && sudo apt-get install texlive

      - name: Check whether LaTeX is installed
        run: pdflatex --version

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4.0.1
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Set up Nomad
        run: |
            cd ./nomad 
            cmake --version 
            cmake -DTEST_OPENMP=OFF -DBUILD_INTERFACE_MATLAB=ON -S . -B build/release
            cmake --build build/release
            cmake --install build/release
            find /usr/lib /lib -name "libstdc++.so.6"

      - name: Set LD_PRELOAD
        run: echo "LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6" >> $GITHUB_ENV

      - name: Run test
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            root_dir = pwd()
            ls

            % Setup optiprofiler
            cd(fullfile(root_dir, 'optiprofiler'));
            setup
            cd(root_dir);

            % Setup bds
            cd(root_dir);
            setup
            cd(fullfile(root_dir, 'tests', 'competitors'));
            addpath(pwd);

            % Setup matcutest
            % cd(fullfile(root_dir, 'matcutest'));
            % install

            % Setup nomad
            cd(fullfile(root_dir, 'nomad', 'build', 'release', 'lib'));
            addpath(pwd);
            
            % Test nomad
            cd(fullfile(root_dir, 'nomad', 'interfaces', 'Matlab_MEX'));
            test_nomad_gerad
            cd(fullfile(root_dir, 'tests', 'competitors'));
            test_nomad_s2mpj
            

            % profile
            % cd(fullfile(root_dir, 'bds', 'tests'));
            % options = struct();
            % options.feature_name = '${{ matrix.feature }}';
            % options.solver_names = {'${{ matrix.solver }}', '${{ matrix.competitor }}'};
            % options.dim = '${{ matrix.dim }}';
            % options.run_plain = ${{ matrix.run_plain }};
            % profile_optiprofiler(options);
            % cd(root_dir);

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: profile_optiprofiler_${{ matrix.solver }}_${{ matrix.competitor }}_${{ matrix.dim }}_${{ matrix.feature }}_${{ matrix.run_plain }}
          path: ./bds/tests/out/**
