name: Stress test

on:
  # Trigger the workflow on push or pull request
  # push:
  # Trigger the workflow manually
  schedule:
    - cron: '0 21 */2 * *'
  workflow_dispatch:

jobs:
  test:
    name: Stress test
    runs-on: ${{matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        matlab: [R2021a, R2022a, R2023a]#, latest]
        with_optim_toolbox: [no]
        solver: [CBDS, PBDS, RBDS, DS]
        tough: [true, false]
        exclude:
          - os: windows-latest
            matlab: R2021a

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v4.0.1
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB 
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ matrix.matlab }}

      - name: Run test
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            root_dir = pwd()

            % Conduct your tests
            path_tests = fullfile(root_dir, 'tests');
            cd(path_tests);

            % Run tests
            options.Algorithm = "${{ matrix.solver }}";
            options.tough = ${{ matrix.tough }};
            stress("bds", options);
