name: Test StepTolerance for bds

on:
  # Trigger the workflow on push or pull request
  # push:
  # Trigger the workflow manually
  #schedule:
  # - cron: '0 12 */7 * *'
  workflow_dispatch:

jobs:
  test:
    name: Set StepTolerance for bds
    runs-on: ${{matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        with_optim_toolbox: [yes]
        Algorithm: [cbds, rbds, pbds]
        StepTolerance: [eps, 1e-14, 1e-12, 1e-10, 1e-8, 1e-6]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Clone MatCUTEst
        uses: actions/checkout@v4
        with:
          repository: matcutest/matcutest_compiled
          path: matcutest

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3.3.3
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Run test
        uses: matlab-actions/run-command@v1.2.2
        with:
          command: |
            root_dir = pwd()

            % Install MatCUTEst
            cd(fullfile(root_dir, 'matcutest'));
            install(); cd(root_dir);

            % Conduct your tests
            path_tests = fullfile(root_dir, 'tests');
            cd(path_tests)

            Algorithm = "${{ matrix.Algorithm }}";
            options.StepTolerance = ${{ matrix.StepTolerance }};
            test_StepTolerance(Algorithm, options);

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test_StepTolerance
          path: ./tests/testdata
