name: Performance profiles of Prima on problems of small dimensions with noise

on:
  # Trigger the workflow on push or pull request
  # push:
  # Trigger the workflow manually
  schedule:
    - cron: '0 22 */3 * *'
  workflow_dispatch:

env:
    GFORTRAN_VERSION: 12

jobs:
  test:
    name: Profile blockwise direct search.
    runs-on: ${{matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        dim: [small]
        with_optim_toolbox: [yes]
        solver: [bobyqa]
        competitor: [newuoa, lincoa]
        noise_level: [negligible, low, medium, high]
        version: [old, now]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clone MatCUTEst
        uses: actions/checkout@v3
        with:
          repository: equipez/matcutest_compiled
          path: matcutest

      - name: Clone PRIMA
        uses: actions/checkout@v3
        with:
          repository: libprima/prima
          path: prima

      - name: Link gfortran for MATLAB on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: bash .github/scripts/link_gfortran ${{ env.GFORTRAN_VERSION }}

      - name: Install epstopdf and ghostscript
        if: startsWith(matrix.os, 'ubuntu')
        run: bash .github/scripts/install_epstopdf && bash .github/scripts/install_ghostscript

      - name: Install Texlive
        run: sudo apt-get update && sudo apt-get install texlive

      - name: Check whether LaTeX is installed
        run: pdflatex --version

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3.3.1
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}-${{ matrix.with_optim_toolbox }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox

      - name: Run test
        uses: matlab-actions/run-command@v1.2.0
        with:
          command: |
            root_dir = pwd()

            % Install MatCUTEst
            cd(fullfile(root_dir, 'matcutest'));
            install(); cd(root_dir);

            % Compile prima
            path_prima = fullfile(root_dir, 'prima');
            cd(path_prima);
            setup

            % Conduct your tests
            path_tests = fullfile(root_dir, 'tests');
            cd(path_tests)
            parameters.problems_dim = "${{ matrix.dim }}";
            parameters.parallel = true;
            parameters.StepTolerance = eps;
            parameters.version = "${{ matrix.version }}";
            parameters.is_noisy = true;
            parameters.noise_level = "${{ matrix.noise_level }}";
            parameters.num_random = 5;
            parameters.solvers_invoke = ["${{ matrix.solver }}", "${{ matrix.competitor }}"];
            profile_bds(parameters);

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test_prima_small_with_noise
          path: ./tests/testdata
